-- MySQL Script generated by MySQL Workbench
-- Wed Apr 18 21:28:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agenda` DEFAULT CHARACTER SET utf8 ;
USE `agenda` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbl_cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`tbl_cidades` (
  `id` INT NOT NULL,
  `nome_cidade` VARCHAR(60) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`tbl_usuarios` (
  `id` INT NOT NULL,
  `nome_usuario` VARCHAR(30) NOT NULL,
  `senha` CHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_contatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`tbl_contatos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `endereco` VARCHAR(60) NOT NULL,
  `nro_endereco` INT NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `cidade_id` INT NOT NULL,
  `cep` CHAR(9) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_contatos_tbl_cidades_idx` (`cidade_id` ASC),
  CONSTRAINT `fk_tbl_contatos_tbl_cidades`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `agenda`.`tbl_cidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agenda`.`tbl_telefones` (
  `id` INT NOT NULL,
  `contato_id` INT NOT NULL,
  `tipo_telefone` VARCHAR(11) NOT NULL,
  `nro_telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_telefones_tbl_contatos1_idx` (`contato_id` ASC),
  CONSTRAINT `fk_tbl_telefones_tbl_contatos1`
    FOREIGN KEY (`contato_id`)
    REFERENCES `agenda`.`tbl_contatos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
